### ISSUE TITLE
Expanded Xenoblade Chronicles X (EUR) cache submission

### ISSUE THREAD

**Issue by romatthe** [chriztr/cemu_shader_and_pipeline_caches#11]
Since I'm not much of a Reddit or Discord user, I decided to contact you this way.

I've submitted my generated Vulkan shaders and pipelines for Xenoblade Chronicles X (EUR) [00050000101c4c00] via PR #10.

The site already contains a shader cache for this title, but it was generated by playing the game for only a few hours. I completed the game yesterday after about 65+ hours of playtime. I definitely didn't do everything, but I think this cache should cover a lot if not most of what CEMU will output.

Small note: most of this was generated on Linux on one of the newer 2.0+ release candidates. This should not matter at all, but I imported the cache into my Windows installation on my laptop for verification, and everything compiled just fine, I warped across the game for about 30 minutes and everything looked just fine.

Additional info:

**Generated on:**
CEMU 2.0-13 Linux
OS: NixOS 22.05, Kernel 6.0.9
CPU: AMD Ryzen 9 5900X 12-Core
GPU: AMD Radeon RX 6800 XT 
GPU DRIVER: 4.6 Mesa 22.0.4 (Using RADV, not AMDVLK)

**Verified on:**
CEMU 1.26.2 Windows
OS: Windows 10K
CPU: Intel Core i7-10750H @ 2.60GHz
GPU: Nvidia RTX 2060 (Mobile)

**Comment by chriztr** [comment]
That's all good :)
I'm not much of a github user nor reddit user, but this works just fine.
I took the caches and merged them with what I had and then uploaded them. So whenever github decides to push it, it's live!
Thanks a bunch!
I'll just close the pullrequest, since I dont know any better way to handle it

**Comment by romatthe** [comment]
No problem, I just opened the PR in an attempt to be helpful ;) I probably should have just included a zip or something.
Anyway, glad I could be of use!

**Comment by romatthe** [comment]
I see that the cache is up, so I'll close this issue 😉
