### ISSUE TITLE
Yoshy Woolly World cache

### ISSUE THREAD

**Issue by bell07** [chriztr/cemu_shader_and_pipeline_caches#9]
[Yoshi.zip](https://github.com/chriztr/cemu_shader_and_pipeline_caches/files/9792494/Yoshi.zip)

Played trough Yoshy Woolly World using your caches. In last levels I seen my Cemu did additional compiling.
In attachment my updated transferable files. How is the right way to contribute and/or merge caches?

**Comment by chriztr** [comment]
This way works just fine imo.
I personally like to handle the merging of existing caches and adding them to the list.
Thanks for the support :)
